### PR TITLE
Update Holiday List.md

### PR DESCRIPTION
**Pull request by vinaysshenoy**
Corrected name of a holiday.

### CODE REVIEW

**Comment by pratul** [comment]
@vinaysshenoy Please align the table column markers correctly. Your edit has misaligned the universe.

**Comment by vinaysshenoy** [comment]
> @vinaysshenoy Please align the table column markers correctly. Your edit has misaligned the universe.

Done.

**Comment by vinaysshenoy** [comment]
I looked it up online and realised that the holiday is also called Kannada Rajyotsava sometimes, so it's okay to leave it as is.

**Comment by gonsalves** [comment]
Karnataka sounds better. Merging!

**Pull request merged**
